task:
  retry:
    times: 3
    interval: 1
redis:
  lock:
    interval: 10

mybatis:
  mapperLocations: classpath*:mapper/*Dao.xml
  executor-type: REUSE
spring:
  datasource:
    url: jdbc:mysql://localhost/claim_core?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
  redis:
    host: localhost
    port: 6379
    password: 123456